import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const mode = process.argv[2];
const prod = (mode === "production");
// A production build that a profiler can read: the same code, unminified and
// with its function names kept, so a flame graph says "describeRange" rather
// than "s". Never released; release builds are verified byte for byte.
const profile = (mode === "profile");

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules,
		...builtinModules.map((m) => `node:${m}`)],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod || profile ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	keepNames: profile,
});

if (prod || profile) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
